(function(){
 'use strict';
 const db=window.redmusicaClient;if(!db)return;
 const nav=document.getElementById('navegacion');
 const toggle=document.createElement('button');toggle.type='button';toggle.textContent='Administración';toggle.hidden=true;nav.append(toggle);
 const panel=document.createElement('section');panel.id='administracion';panel.hidden=true;
 panel.innerHTML=`
 <header class="admin-cabecera"><div><p class="admin-kicker">REDMUSICA · CONTROL</p><h2>Panel de administración</h2><p>Modera la comunidad y dirige la radio desde un solo lugar.</p></div><span id="adminRango" class="admin-rango"></span></header>
 <p id="adminEstado" class="admin-estado" role="status" aria-live="polite" data-state="working">Conectando con el panel…</p>
 <div class="admin-resumen" aria-label="Estado del sitio"><article><span>Radio</span><strong id="adminMetricRadio">Consultando</strong></article><article><span>En la cola</span><strong id="adminMetricQueue">—</strong></article><article><span>Publicaciones</span><strong id="adminMetricPosts">Abiertas</strong></article></div>
 <nav class="admin-tabs" aria-label="Herramientas de administración" role="tablist">
  <button type="button" data-admin-view="radio" aria-pressed="true">Radio</button><button type="button" data-admin-view="moderacion" aria-pressed="false">Moderación</button><button type="button" data-admin-view="usuarios" aria-pressed="false">Cuentas</button><button type="button" data-admin-view="historial" aria-pressed="false">Actividad</button><button type="button" data-admin-view="ajustes" aria-pressed="false">Ajustes</button>
 </nav>
 <section class="admin-view" data-admin-panel="radio"><div class="admin-bloque"><div class="admin-bloque-titulo"><div><h3>Cabina de radio</h3><p>Estos controles afectan a todas las personas conectadas.</p></div><button id="adminRadioRefresh" type="button">Actualizar</button></div><div class="admin-acciones"><button id="adminSkip" type="button">Saltar canción actual</button><button id="adminRadioToggle" type="button">Pausar radio</button></div><h4>Sonando y próximos turnos</h4><p class="admin-ayuda">“Poner siguiente” cambia el orden de esta rotación. “Excluir para siempre” retira el video de futuras rotaciones.</p><div id="adminQueue" class="admin-lista"></div></div>
 <div id="adminOwnerExclusion" class="admin-bloque"><div class="admin-bloque-titulo"><div><h3>Excluir video permanentemente</h3><p>Los videos aquí no vuelven a aparecer en la rotación ni en la búsqueda de la radio.</p></div></div><form id="adminBlockForm" class="admin-form-block"><label for="adminBlockVideo">Enlace o ID de YouTube</label><input id="adminBlockVideo" type="text" maxlength="200" placeholder="https://youtube.com/watch?v=…" required><label for="adminBlockTitle">Nombre para reconocerlo</label><input id="adminBlockTitle" type="text" maxlength="300" placeholder="Artista — canción" required><label for="adminBlockReason">Motivo (opcional)</label><input id="adminBlockReason" type="text" maxlength="240" placeholder="Copyright, video bloqueado, reporte…"><button type="submit">Excluir de la radio</button></form>
   <details class="admin-exclusiones"><summary>Videos excluidos <span id="adminBlockedCount"></span></summary><form id="adminBlockedFilter" class="fila-controles"><input id="adminBlockedQuery" maxlength="100" placeholder="Buscar en videos excluidos" aria-label="Buscar en videos excluidos"><button type="submit">Buscar</button></form><div id="adminBlockedSongs" class="admin-lista"></div></details>
  </div></section>
 <section class="admin-view" data-admin-panel="moderacion" hidden><div class="admin-bloque"><div class="admin-bloque-titulo"><div><h3>Contenido de la comunidad</h3><p>Oculta publicaciones, memes, reseñas, eventos, juegos y mensajes públicos. Puedes restaurarlos luego.</p></div><span id="adminResults" class="admin-resultados" aria-live="polite"></span></div><form id="adminFilter" class="admin-buscador"><label for="adminKind">Tipo de contenido</label><select id="adminKind" aria-label="Administrar"><option value="posts">Muro y música</option><option value="memes">Memes</option><option value="films">Reseñas de películas</option><option value="comments">Comentarios</option><option value="events">Eventos</option><option value="games">Juegos recomendados</option><option value="community_chat">Chat comunitario</option></select><label for="adminQuery">Buscar por texto o usuario</label><input id="adminQuery" placeholder="Texto o nombre de usuario" aria-label="Buscar en administración" maxlength="100"><button>Buscar contenido</button></form><p class="admin-ayuda">Ocultar retira el elemento de la vista pública. Puedes restaurarlo desde esta misma lista.</p><div id="adminList" class="admin-lista"></div><div class="admin-paginacion"><button id="adminPrev" type="button">Anterior</button><span id="adminPageLabel" aria-live="polite">Página 1</span><button id="adminNext" type="button">Siguiente</button></div></div></section>
 <section class="admin-view" data-admin-panel="usuarios" hidden><div class="admin-bloque"><h3>Cuentas y rangos</h3><p>Los administradores pueden moderar contenido y cuentas miembros. Solo owner puede asignar rangos.</p><form id="adminUserFilter" class="fila-controles"><label class="solo-lectores" for="adminUserQuery">Buscar cuenta</label><input id="adminUserQuery" placeholder="Buscar usuario" maxlength="100"><button type="submit">Buscar cuentas</button></form><div id="adminUsers" class="admin-lista"></div><div class="admin-paginacion"><button id="adminUsersPrev" type="button">Anterior</button><button id="adminUsersNext" type="button">Siguiente</button></div></div></section>
 <section class="admin-view" data-admin-panel="historial" hidden><div class="admin-bloque"><div class="admin-bloque-titulo"><div><h3>Actividad administrativa</h3><p>Acciones recientes de moderación y control.</p></div><button id="adminAuditRefresh" type="button">Actualizar historial</button></div><div id="adminAudit" class="admin-lista"></div><div class="admin-paginacion"><button id="adminAuditPrev" type="button">Anterior</button><button id="adminAuditNext" type="button">Siguiente</button></div></div></section>
 <section class="admin-view" data-admin-panel="ajustes" hidden><div class="admin-bloque"><h3>Ajustes del sitio</h3><p id="adminAjustesAviso">Cambian lo que ven todas las personas.</p><form id="adminSettings" class="admin-form-settings"><label for="adminTitle">Nombre del sitio</label><input id="adminTitle" maxlength="60" required><label for="adminDescription">Descripción</label><textarea id="adminDescription" maxlength="300"></textarea><label class="admin-check"><input id="adminPosts" type="checkbox"> Permitir nuevas publicaciones</label><label for="adminGiphyKey">Clave pública de GIPHY</label><input id="adminGiphyKey" type="password" maxlength="200" autocomplete="new-password" placeholder="Pega aquí la clave beta de GIPHY"><p id="adminGiphyStatus">La clave configurada se usa en el navegador para buscar GIFs.</p><button>Guardar ajustes</button></form></div></section>`;
 document.getElementById('cuenta').after(panel);
 const $=id=>document.getElementById(id);let role='member',page=0,userPage=0,auditPage=0,paused=false,busy=false,revision=0;
 toggle.setAttribute('aria-controls','administracion');toggle.setAttribute('aria-expanded','false');
 async function call(action,data={}){const {data:auth}=await db.auth.getSession();if(!auth.session)throw Error('Inicia sesión.');const r=await fetch(window.REDMUSICA_CONFIG.supabaseUrl+'/functions/v1/admin',{method:'POST',headers:{'Content-Type':'application/json',apikey:window.REDMUSICA_CONFIG.supabasePublishableKey,Authorization:'Bearer '+auth.session.access_token},body:JSON.stringify({action,data}),signal:AbortSignal.timeout(15000)});const value=await r.json();if(!r.ok)throw Error(value.error||'No se pudo completar la acción.');return value;}
 async function action(work){if(busy)return;busy=true;panel.setAttribute('aria-busy','true');const status=$('adminEstado');status.dataset.state='working';status.textContent='Procesando…';try{await work();status.dataset.state='success';status.textContent='Listo.';}catch(e){status.dataset.state='error';status.textContent=e.message||'No se pudo completar la acción.';}finally{busy=false;panel.removeAttribute('aria-busy');}}
 function button(label,work,kind=''){const b=document.createElement('button');b.type='button';b.textContent=label;if(kind){b.className=kind;if(kind==='admin-boton-peligro')b.hidden=role!=='owner';}b.addEventListener('click',()=>action(work));return b;}
 function line(text,tag='p'){const el=document.createElement(tag);el.textContent=text;return el;}
 async function settings(){const {data,error}=await db.from('site_settings').select('*').eq('id',1).maybeSingle();if(error||!data||typeof data.title!=='string')return;document.querySelector('main > h1').textContent=data.title;document.querySelector('main > p').textContent=data.description;$('adminTitle').value=data.title;$('adminDescription').value=data.description;$('adminPosts').checked=data.accept_posts;$('adminMetricPosts').textContent=data.accept_posts?'Abiertas':'Pausadas';const gifSetting=await db.from('site_gif_settings').select('api_key').eq('id',true).maybeSingle();$('adminGiphyStatus').textContent=gifSetting.data?.api_key?'Hay una clave pública de GIPHY configurada.':'Todavía no hay una clave de GIPHY; las búsquedas permanecerán desactivadas.';}
 async function fetchList(kind,query,offset){return (await call('list',{kind,offset:offset*30,query})).items||[];}
 async function contentList(){const ticket=revision,kind=$('adminKind').value,items=await fetchList(kind,$('adminQuery').value,page);if(ticket!==revision)return;$('adminList').replaceChildren();$('adminPrev').disabled=page===0;$('adminNext').disabled=items.length<30;$('adminPageLabel').textContent='Página '+(page+1);$('adminResults').textContent=items.length?items.length+' en esta página':'';const names={posts:'Publicación',memes:'Meme',films:'Película',comments:'Comentario',events:'Evento',games:'Juego',community_chat:'Chat comunitario'};for(const item of items){const row=document.createElement('article');row.className='admin-fila';row.classList.toggle('admin-fila-oculta',Boolean(item.hidden));const subject=[item.album_title,item.film_title,item.title,item.platform].filter(Boolean).join(' · ');row.append(line('@'+(item.username||'cuenta eliminada')+' · '+names[kind]+(subject?' · '+subject:''),'strong'),line(item.body||'(sin texto)'),line(item.hidden?'Oculto para la comunidad':'Visible para la comunidad','small'));if(item.created_at)row.append(line(new Date(item.created_at).toLocaleString('es-CL'),'time'));row.append(button(item.hidden?'Restaurar':'Ocultar',async()=>{await call('moderate',{kind,id:item.id,hidden:!item.hidden});await contentList();$('actualizarFeed')?.click();}));$('adminList').append(row);}if(!items.length){$('adminResults').textContent='0 resultados';$('adminList').append(line('No hay resultados para esta búsqueda.'));}}
 async function usersList(){const ticket=revision,items=await fetchList('users',$('adminUserQuery').value,userPage);if(ticket!==revision)return;$('adminUsers').replaceChildren();$('adminUsersPrev').disabled=userPage===0;$('adminUsersNext').disabled=items.length<30;for(const item of items){const row=document.createElement('article');row.className='admin-fila';row.append(line('@'+item.username,'strong'),line((item.role==='owner'?'Owner':item.role==='admin'?'Administrador':'Miembro')+(item.suspended?' · Suspendida':''),'small'));if(item.role!=='owner'){row.append(button(item.suspended?'Reactivar cuenta':'Suspender cuenta',async()=>{if(!confirm('¿Cambiar el acceso de @'+item.username+'?'))return;await call('suspend',{id:item.id,suspended:!item.suspended});await usersList();}));if(role==='owner')row.append(button(item.role==='admin'?'Retirar administración':'Hacer administrador',async()=>{if(!confirm('¿Cambiar el rango de @'+item.username+'?'))return;await call('role',{id:item.id,role:item.role==='admin'?'member':'admin'});await usersList();}));}$('adminUsers').append(row);}if(!items.length)$('adminUsers').append(line('No se encontraron cuentas.'));}
 async function auditList(){const ticket=revision,items=await fetchList('audit','',auditPage);if(ticket!==revision)return;$('adminAudit').replaceChildren();$('adminAuditPrev').disabled=auditPage===0;$('adminAuditNext').disabled=items.length<30;for(const item of items){const row=document.createElement('article');row.className='admin-fila';row.append(line('@'+(item.username||'cuenta eliminada')+' · '+item.action,'strong'),line(new Date(item.created_at).toLocaleString('es-CL')));$('adminAudit').append(row);}if(!items.length)$('adminAudit').append(line('Aún no hay acciones registradas.'));}
 async function blockedList(){const items=await fetchList('blocked_songs',$('adminBlockedQuery').value,0);$('adminBlockedSongs').replaceChildren();$('adminBlockedCount').textContent=items.length?'· '+items.length:'';for(const song of items){const row=document.createElement('article');row.className='admin-fila admin-fila-cancion';const title=document.createElement('strong'),meta=line((song.channel||'Canal desconocido')+' · '+song.reason,'small'),link=document.createElement('a');title.textContent=song.title;link.href='https://www.youtube.com/watch?v='+encodeURIComponent(song.video_id);link.target='_blank';link.rel='noopener';link.textContent='Ver video';row.append(title,meta,link,button('Permitir de nuevo',async()=>{if(!confirm('¿Permitir que este video vuelva a aparecer en la radio?'))return;await call('unblock_song',{video_id:song.video_id});await blockedList();}));$('adminBlockedSongs').append(row);}if(!items.length)$('adminBlockedSongs').append(line('No hay videos excluidos.'));}
 function youtubeId(value){const raw=value.trim();if(/^[A-Za-z0-9_-]{11}$/.test(raw))return raw;try{const url=new URL(raw);if(url.hostname==='youtu.be')return url.pathname.slice(1,12);if(url.hostname.endsWith('youtube.com'))return url.searchParams.get('v')||url.pathname.split('/').filter(Boolean).pop()||'';}catch{}return '';}
 async function radio(){const ticket=revision,r=await fetch(window.REDMUSICA_CONFIG.supabaseUrl+'/functions/v1/radio',{method:'POST',headers:{'Content-Type':'application/json',apikey:window.REDMUSICA_CONFIG.supabasePublishableKey},body:JSON.stringify({action:'state'}),signal:AbortSignal.timeout(15000)}),data=await r.json();if(!r.ok)throw Error(data.error||'No se pudo consultar la radio.');if(ticket!==revision)return;paused=data.paused;$('adminRadioToggle').textContent=paused?'Reanudar radio':'Pausar radio';$('adminMetricRadio').textContent=paused?'Pausada':'En vivo';$('adminMetricQueue').textContent=String(data.queue.length);$('adminQueue').replaceChildren();if(!data.queue.length)$('adminQueue').append(line('No hay canciones en la cola.'));for(const [index,s] of data.queue.entries()){const row=document.createElement('article');row.className='admin-fila admin-fila-cancion';const title=document.createElement('strong');title.textContent=(index===0?'▶ Sonando · ':'')+s.title;row.append(title,line((s.channel||'Canal')+' · '+(s.username?'pedido por @'+s.username:'rotación'), 'small'));const link=document.createElement('a');link.href='https://www.youtube.com/watch?v='+encodeURIComponent(s.video_id);link.target='_blank';link.rel='noopener';link.textContent='Ver video';row.append(link);for(const [label,cmd] of [['Poner siguiente','priority'],['Quitar de cola','remove']])row.append(button(label,async()=>{if(cmd==='remove'&&!confirm('¿Quitar esta canción solo de la cola actual?'))return;await call(cmd,{id:s.id});await radio();}));row.append(button('Excluir para siempre',async()=>{if(!confirm('Este video quedará bloqueado para todos y se quitará de la rotación. ¿Continuar?'))return;await call('block_song',{video_id:s.video_id,title:s.title,channel:s.channel,reason:'Retirada desde la cabina de radio'});await radio();await blockedList();},'admin-boton-peligro'));$('adminQueue').append(row);}}
 function selectView(name,focus=false){panel.querySelectorAll('[data-admin-view]').forEach(b=>{const active=b.dataset.adminView===name;b.setAttribute('aria-pressed',String(active));b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(focus&&active)b.focus();});panel.querySelectorAll('[data-admin-panel]').forEach(section=>section.hidden=section.dataset.adminPanel!==name);}
 toggle.addEventListener('click',()=>{panel.hidden=!panel.hidden;toggle.setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)action(async()=>{await settings();await radio();await contentList();await usersList();await auditList();if(role==='owner')await blockedList();});});
 panel.querySelectorAll('[data-admin-view]').forEach(tab=>{const target=panel.querySelector('[data-admin-panel="'+tab.dataset.adminView+'"]');tab.setAttribute('role','tab');tab.setAttribute('aria-controls',target.id||'admin-view-'+tab.dataset.adminView);target.id=target.id||'admin-view-'+tab.dataset.adminView;tab.setAttribute('aria-selected',String(tab.getAttribute('aria-pressed')==='true'));tab.tabIndex=tab.getAttribute('aria-pressed')==='true'?0:-1;tab.addEventListener('click',()=>selectView(tab.dataset.adminView));tab.addEventListener('keydown',e=>{const tabs=[...panel.querySelectorAll('[data-admin-view]:not([hidden])')],index=tabs.indexOf(tab);let next;if(e.key==='ArrowRight')next=tabs[(index+1)%tabs.length];else if(e.key==='ArrowLeft')next=tabs[(index-1+tabs.length)%tabs.length];else if(e.key==='Home')next=tabs[0];else if(e.key==='End')next=tabs[tabs.length-1];if(next){e.preventDefault();selectView(next.dataset.adminView,true);}});});panel.querySelectorAll('[data-admin-panel]').forEach(section=>{section.setAttribute('role','tabpanel');section.setAttribute('tabindex','0');section.setAttribute('aria-label',panel.querySelector('[data-admin-view="'+section.dataset.adminPanel+'"]').textContent.trim());});
 $('adminFilter').addEventListener('submit',e=>{e.preventDefault();page=0;action(contentList);});$('adminPrev').addEventListener('click',()=>{if(page){page--;action(contentList);}});$('adminNext').addEventListener('click',()=>{page++;action(contentList);});
 $('adminUserFilter').addEventListener('submit',e=>{e.preventDefault();userPage=0;action(usersList);});$('adminUsersPrev').addEventListener('click',()=>{if(userPage){userPage--;action(usersList);}});$('adminUsersNext').addEventListener('click',()=>{userPage++;action(usersList);});
 $('adminAuditRefresh').addEventListener('click',()=>{auditPage=0;action(auditList);});$('adminAuditPrev').addEventListener('click',()=>{if(auditPage){auditPage--;action(auditList);}});$('adminAuditNext').addEventListener('click',()=>{auditPage++;action(auditList);});
 $('adminRadioRefresh').addEventListener('click',()=>action(async()=>{await radio();if(role==='owner')await blockedList();}));$('adminSkip').addEventListener('click',()=>action(async()=>{if(!confirm('¿Saltar la canción para todos?'))return;await call('skip');await radio();}));$('adminRadioToggle').addEventListener('click',()=>action(async()=>{await call('radio_toggle',{enabled:paused});await radio();}));
 $('adminBlockForm').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,video_id=youtubeId($('adminBlockVideo').value);if(!video_id){$('adminEstado').textContent='Pega un enlace de YouTube válido o su ID de 11 caracteres.';return;}action(async()=>{await call('block_song',{video_id,title:$('adminBlockTitle').value.trim(),reason:$('adminBlockReason').value.trim()});form.reset();await radio();await blockedList();});});$('adminBlockedFilter').addEventListener('submit',e=>{e.preventDefault();action(blockedList);});
 $('adminSettings').addEventListener('submit',e=>{e.preventDefault();action(async()=>{await call('settings',{title:$('adminTitle').value,description:$('adminDescription').value,accept_posts:$('adminPosts').checked});const key=$('adminGiphyKey').value.trim();if(key){const {error}=await db.rpc('set_giphy_api_key',{p_key:key});if(error)throw error;$('adminGiphyKey').value='';}await settings();});});
async function sync(){const ticket=++revision;toggle.hidden=true;panel.hidden=true;toggle.setAttribute('aria-expanded','false');for(const id of ['adminList','adminUsers','adminAudit','adminQueue','adminBlockedSongs'])$(id).replaceChildren();try{const me=await call('me');if(ticket!==revision)return;role=me.role;toggle.hidden=!['owner','admin'].includes(role);toggle.textContent=role==='owner'?'Panel owner':'Administración';$('adminRango').textContent=role==='owner'?'OWNER · Control completo':'ADMIN · Moderación';panel.querySelector('[data-admin-view="usuarios"]').hidden=role!=='owner';panel.querySelector('[data-admin-view="historial"]').hidden=role!=='owner';panel.querySelector('[data-admin-view="ajustes"]').hidden=role!=='owner';panel.querySelector('[data-admin-panel="usuarios"]').hidden=true;panel.querySelector('[data-admin-panel="historial"]').hidden=true;panel.querySelector('[data-admin-panel="ajustes"]').hidden=true;$('adminOwnerExclusion').hidden=role!=='owner';}catch{role='member';}}
 db.auth.onAuthStateChange(()=>setTimeout(sync,0));sync();
})();
