const {chromium,webkit,devices}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{for(const engine of [chromium,webkit]){
 const browser=await engine.launch();const page=await browser.newPage(engine===webkit?devices['iPhone 13']:{viewport:{width:1200,height:900}});const errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.route('https://test.invalid/**',r=>{if(r.request().method()==='GET')return r.fulfill({contentType:'text/html',body:'<html><body></body></html>'});const b=r.request().postDataJSON();calls.push(b);if(b.action==='list'&&b.data.query==='error')return r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Error de prueba'})});let data={ok:true};if(b.action==='me')data={role:'owner'};if(b.action==='list')data={items:b.data.kind==='users'?[{id:'member',username:'Ana',role:'member',suspended:false},{id:'owner',username:'Kattomon',role:'owner'}]:b.data.kind==='posts'?[{id:'post',username:'Ana',body:'Opinión',hidden:false,created_at:'2026-09-29T12:00:00Z'}]:[]};if(b.action==='state')data={paused:false,queue:[{id:'song',video_id:'abcdefghijk',title:'Canción',channel:'Canal',username:'Ana'}]};return r.fulfill({contentType:'application/json',body:JSON.stringify(data)});});
 await page.goto('https://test.invalid/');await page.setContent('<main><h1>RedMusica</h1><p>Descripción</p><nav id="navegacion"></nav><aside id="radioEnVivo">En vivo</aside><section id="cuenta"></section><button id="actualizarFeed">Actualizar</button></main>');
 await page.addStyleTag({content:fs.readFileSync('style.css','utf8')});
 await page.evaluate(()=>{window.REDMUSICA_CONFIG={supabaseUrl:'https://test.invalid',supabasePublishableKey:'test'};window.redmusicaClient={auth:{getSession:async()=>({data:{session:{access_token:'test'}}}),onAuthStateChange:cb=>window.authChange=cb},from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{title:'RedMusica',description:'Descripción',accept_posts:true}})})})})};});
 await page.addScriptTag({content:fs.readFileSync('admin.js','utf8')});
 await page.getByRole('button',{name:'Panel owner'}).click();await page.waitForURL('**/?seccion=administracion');assert.equal(await page.locator('#cuenta').isVisible(),false);assert.equal(await page.locator('#radioEnVivo').isVisible(),true);assert.equal(await page.locator('#administracion').evaluate(el=>el.previousElementSibling.id),'radioEnVivo');await page.locator('#adminVolver').click();assert.equal(await page.locator('#cuenta').isVisible(),true);await page.getByRole('button',{name:'Panel owner'}).click();await page.goBack();assert.equal(await page.locator('#cuenta').isVisible(),true);await page.goForward();assert.equal(await page.locator('#administracion').isVisible(),true);await page.getByRole('tab',{name:'Moderación'}).click();await page.getByText('Opinión',{exact:true}).waitFor();assert.equal(await page.getByRole('tab',{name:'Moderación'}).getAttribute('aria-selected'),'true');assert.equal(await page.locator('#adminPageLabel').textContent(),'Página 1');await page.getByRole('button',{name:'Ocultar',exact:true}).click();await page.getByText('Listo.',{exact:true}).waitFor();assert(calls.some(c=>c.action==='moderate'));
 await page.locator('#adminQuery').fill('error');await page.getByRole('button',{name:'Buscar contenido'}).click();await page.getByText('Error de prueba',{exact:true}).waitFor();assert.equal(await page.locator('#adminEstado').getAttribute('data-state'),'error');await page.locator('#adminQuery').fill('');await page.getByRole('button',{name:'Buscar contenido'}).click();await page.getByText('Opinión',{exact:true}).waitFor();
 await page.getByRole('tab',{name:'Cuentas'}).click();await page.getByRole('button',{name:'Buscar cuentas'}).click();await page.getByRole('button',{name:'Hacer administrador'}).click();await page.getByText('Listo.',{exact:true}).waitFor();assert(calls.some(c=>c.action==='role'&&c.data.id==='member'));
 await page.getByRole('tab',{name:'Radio'}).click();await page.getByRole('button',{name:'Excluir para siempre'}).click();await page.getByText('Listo.',{exact:true}).waitFor();assert(calls.some(c=>c.action==='block_song'&&c.data.video_id==='abcdefghijk'));
 await page.getByRole('tab',{name:'Radio'}).focus();await page.keyboard.press('ArrowRight');assert.equal(await page.getByRole('tab',{name:'Moderación'}).getAttribute('aria-selected'),'true');await page.getByRole('tab',{name:'Radio'}).click();
 await page.locator('#adminBlockVideo').fill('https://youtu.be/abcdefghij2');await page.locator('#adminBlockTitle').fill('Otra canción');await page.locator('#adminBlockForm').evaluate(form=>form.requestSubmit());await page.getByText('Listo.',{exact:true}).waitFor();assert(calls.some(c=>c.action==='block_song'&&c.data.video_id==='abcdefghij2'));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.evaluate(()=>{window.redmusicaClient.auth.getSession=async()=>({data:{session:null}});window.authChange();});await page.getByRole('button',{name:'Panel owner'}).waitFor({state:'hidden'});assert.equal(await page.locator('#administracion').isVisible(),false);assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS '+engine.name()+': owner panel, moderation, roles, DJ, logout, responsive');
}})().catch(e=>{console.error(e);process.exit(1)});
