const { PGlite } = require(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
 const db = new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users (id uuid primary key, raw_user_meta_data jsonb);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth, public to anon, authenticated;
 grant execute on function auth.uid() to anon, authenticated;`);
 await db.exec(fs.readFileSync('supabase/schema.sql','utf8').replace(/^\uFEFF/,''));
 const ana='11111111-1111-4111-8111-111111111111', luis='22222222-2222-4222-8222-222222222222';
 await db.query('insert into auth.users values ($1,$2),($3,$4)',[ana,{username:'Ana'},luis,{username:'Luis'}]);
 async function user(id) { await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated'); }
 await user(ana);
 const post=(await db.query("insert into public.posts(album_id,album_title,album_artist,body) values ('33333333-3333-4333-8333-333333333333','Album','Artista','Opinión') returning id,user_id")).rows[0];
 assert.equal(post.user_id,ana);
 await db.query('insert into public.likes(post_id) values ($1)',[post.id]);
 await assert.rejects(db.query('insert into public.likes(post_id) values ($1)',[post.id]));
 await assert.rejects(db.query('insert into public.likes(post_id,user_id) values ($1,$2)',[post.id,luis]));
 await assert.rejects(db.query("update public.posts set user_id=$1 where id=$2",[luis,post.id]));
 await assert.rejects(db.query("insert into public.posts(album_id,album_title,album_artist,body) values ('33333333-3333-4333-8333-333333333333','Album','Artist','   ')"));
 await user(luis);
 assert.equal((await db.query('update public.posts set body=$1 where id=$2 returning id',['hack',post.id])).rows.length,0);
 assert.equal((await db.query('delete from public.posts where id=$1 returning id',[post.id])).rows.length,0);
 assert.equal((await db.query('delete from public.likes where post_id=$1 returning post_id',[post.id])).rows.length,0);
 await db.query('insert into public.likes(post_id) values ($1)',[post.id]);
 await db.query('insert into public.comments(post_id,body) values ($1,$2)',[post.id,'Comentario de Luis']);
 await assert.rejects(db.query('insert into public.comments(post_id,user_id,body) values ($1,$2,$3)',[post.id,ana,'suplantación']));
 await assert.rejects(db.query('update public.profiles set username=$1 where id=$2',['Otro',ana]));
 await db.exec('reset role; set role anon');
 assert.equal((await db.query('select body from public.posts')).rows[0].body,'Opinión');
 await assert.rejects(db.query('insert into public.likes(post_id) values ($1)',[post.id]));
 await user(ana);
 assert.equal((await db.query('update public.posts set body=$1 where id=$2 returning body',['Editado',post.id])).rows[0].body,'Editado');
 await db.query('delete from public.posts where id=$1',[post.id]);
 assert.equal((await db.query('select * from public.comments')).rows.length,0);
 assert.equal((await db.query('select * from public.likes')).rows.length,0);
 await db.exec('reset role');
 await assert.rejects(db.query('insert into auth.users values ($1,$2)',['44444444-4444-4444-8444-444444444444',{username:'ana'}]));
 await assert.rejects(db.query('insert into auth.users values ($1,$2)',['44444444-4444-4444-8444-444444444444',{username:'<script>'}]));
 await db.close();console.log('PASS PostgreSQL: public reads, authenticated writes, ownership, immutable authors, unique likes/usernames, validation and cascades');
})().catch(e=>{console.error(e);process.exit(1)});
