const {chromium,webkit,devices}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const server=http.createServer((req,res)=>{const file=path.join(process.cwd(),new URL(req.url,'http://localhost').pathname);if(!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});
(async()=>{
 await new Promise(r=>server.listen(4180,'127.0.0.1',r));
 for(const engine of [chromium,webkit]){
  const browser=await engine.launch();const ctx=await browser.newContext(engine===webkit?{...devices['iPhone 13']}:{viewport:{width:1200,height:900}});
  let queue=[],searches=0,requests=0;const errors=[];
  await ctx.route('**/vendor/supabase-2.117.2.js',r=>r.fulfill({contentType:'text/javascript',body:`window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'test',user:{id:'listener'}}}}),onAuthStateChange:()=>{}}})};`}));
  await ctx.route('**/functions/v1/radio',r=>{const body=r.request().postDataJSON();let result={now:new Date().toISOString(),queue};if(body.action==='search'){searches++;assert.equal(body.query,'Candelabro Refugio');result={songs:[{video_id:'abcdefghijk',title:'Candelabro &amp; amigos — Refugio',channel:'Candelabro',duration:180,thumbnail:'https://i.ytimg.com/vi/abcdefghijk/hqdefault.jpg'}]};}if(body.action==='request'){requests++;queue=[{id:'one',video_id:body.video_id,title:'Candelabro — Refugio',channel:'Candelabro',duration:180,starts_at:new Date(Date.now()-1000).toISOString(),ends_at:new Date(Date.now()+179000).toISOString(),username:'Ana'}];result={now:new Date().toISOString(),queue};}return r.fulfill({contentType:'application/json',body:JSON.stringify(result)});});
  await ctx.route('https://www.youtube.com/iframe_api',r=>r.fulfill({contentType:'text/javascript',body:`window.YT={Player:function(id,options){window.playerOptions=options;window.playerCalls=[];window.volumeCalls=[];window.pauseCalls=0;window.playCalls=0;this.cueVideoById=p=>window.playerCalls.push(p);this.loadVideoById=p=>window.playerCalls.push(p);this.pauseVideo=()=>window.pauseCalls++;this.playVideo=()=>window.playCalls++;this.stopVideo=()=>{};this.setVolume=v=>window.volumeCalls.push(v);this.mute=()=>window.muted=true;this.unMute=()=>window.muted=false;document.getElementById(id).textContent='Reproductor visible';setTimeout(()=>options.events.onReady(),0);}};window.onYouTubeIframeAPIReady();`}));
  const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4180/radio.html');
  await page.getByText('Todavía no hay canciones. Haz el primer pedido.').waitFor();
  await page.locator('#radioArtista').fill('Candelabro');await page.locator('#radioCancion').fill('Refugio');await page.getByRole('button',{name:'Buscar en YouTube'}).click();
  const thumbnail=page.locator('#radioResultados img.radio-video-thumbnail');await thumbnail.waitFor();assert.match(await thumbnail.getAttribute('src'),/i\.ytimg\.com\/vi\/abcdefghijk\/hqdefault\.jpg/);
  await page.getByRole('button',{name:'Agregar a la cola'}).click();await page.getByText('Canción agregada a la cola compartida.').waitFor();
  assert.match(await page.locator('#radioCola').innerText(),/Ana/);assert.equal(searches,1);assert.equal(requests,1);
  await page.getByRole('button',{name:'Entrar a escuchar'}).click();await page.getByRole('button',{name:'Volver a la canción de la sala'}).waitFor();
  assert.equal(await page.locator('#radioReproductor').isVisible(),true);
  await page.locator('#radioVolumen').evaluate(el=>{el.value='37';el.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await page.locator('#radioVolumenValor').innerText(),'37%');assert.equal(await page.evaluate(()=>window.volumeCalls.at(-1)),37);assert.equal(await page.evaluate(()=>localStorage.getItem('redmusica:radio-volume:v1:listener')),'37');
  assert.equal(await page.evaluate(()=>window.playerCalls[0].videoId),'abcdefghijk');
  await page.evaluate(()=>window.playerOptions.events.onAutoplayBlocked());assert.match(await page.locator('#radioPlayback').innerText(),/pulsa reproducir/);
  const other=await ctx.newPage();await other.goto('http://127.0.0.1:4180/radio.html');await other.locator('#radioCola li').waitFor();assert.match(await other.locator('#radioCola').innerText(),/Refugio/);assert.equal(await other.locator('#radioVolumen').inputValue(),'37','each signed-in listener restores their own saved volume on another page');
  queue=[{...queue[0],id:'two',video_id:'abcdefghij2',title:'Siguiente canción',starts_at:new Date(Date.now()-1000).toISOString(),ends_at:new Date(Date.now()+179000).toISOString()}];
  await page.evaluate(()=>window.playerOptions.events.onStateChange({data:0}));
  await page.waitForFunction(()=>window.playerCalls.some(p=>p.videoId==='abcdefghij2'));
  queue.push({...queue[0],id:'three',video_id:'abcdefghij3',title:'Canción después del bloqueo',starts_at:new Date(Date.now()+180000).toISOString(),ends_at:new Date(Date.now()+360000).toISOString()});
  await page.evaluate(()=>window.playerOptions.events.onError({data:150}));
  assert.equal(await page.evaluate(()=>window.playerCalls.some(p=>p.videoId==='abcdefghij3')),false,'the local player must not play a future queue item before its scheduled time');
  await page.waitForFunction(()=>document.querySelector('#radioProximo').textContent.includes('Canción después del bloqueo'));
  queue[0].ends_at=new Date(Date.now()-1000).toISOString();queue[1].starts_at=new Date(Date.now()-1000).toISOString();queue[1].ends_at=new Date(Date.now()+179000).toISOString();
  await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));
  await page.waitForFunction(()=>window.playerCalls.some(p=>p.videoId==='abcdefghij3'));
  assert.ok(await page.evaluate(()=>window.playerCalls.at(-1).startSeconds)<=5,'the player should join the scheduled live track near its current position');
  assert.match(await page.locator('#radioEscuchando').innerText(),/después del bloqueo/);
  await page.locator('#radioOtraVersion').click();
  assert.equal(await page.locator('#radioCancion').inputValue(),'Siguiente canción');
  await page.evaluate(()=>window.playerOptions.events.onError({data:153}));
  assert.match(await page.locator('#radioPlayback').innerText(),/identificar/);
  await page.getByRole('button',{name:'Volver a la canción de la sala'}).click();
  await page.evaluate(()=>window.playerOptions.events.onError({data:100}));
  await page.getByText(/No quedan canciones reproducibles/).waitFor();
  const count=await page.evaluate(()=>window.playerCalls.length);
  await page.getByRole('button',{name:'Volver a la canción de la sala'}).click();
  assert.equal(await page.evaluate(()=>window.playerCalls.length),count,'Blocked videos must not retry');
  queue=[{...queue[0],id:'cancel-me',user_id:'listener',starts_at:new Date(Date.now()+60000).toISOString()}];
  await ctx.route('**/functions/v1/admin',r=>{assert.deepEqual(r.request().postDataJSON(),{action:'cancel_request',data:{id:'cancel-me'}});queue=[];return r.fulfill({contentType:'application/json',body:'{"ok":true}'});});
  const cancelPage=await ctx.newPage();await cancelPage.goto('http://127.0.0.1:4180/radio.html');await cancelPage.getByRole('button',{name:'Cancelar mi pedido'}).click();await cancelPage.getByText('Todavía no hay canciones. Haz el primer pedido.').waitFor();
  queue=[{id:'live-one',video_id:'lmnopqrstuv',title:'Canción de la sala',channel:'Canal',duration:180,starts_at:new Date(Date.now()-1000).toISOString(),ends_at:new Date(Date.now()+179000).toISOString()}];
  const live=await ctx.newPage();await live.goto('http://127.0.0.1:4180/radio.html');await live.getByRole('button',{name:'Entrar a escuchar'}).click();await live.getByRole('button',{name:'Volver a la canción de la sala'}).waitFor();
  queue=[{id:'live-two',video_id:'ponmlkjihgf',title:'La que suena al volver',channel:'Canal',duration:180,starts_at:new Date(Date.now()-1000).toISOString(),ends_at:new Date(Date.now()+179000).toISOString()}];
  await live.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
  assert.equal(await live.evaluate(()=>window.pauseCalls),0,'the app must not pause playback when the tab is hidden');
  await live.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});
  await live.waitForFunction(()=>window.playerCalls.some(p=>p.videoId==='ponmlkjihgf'));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);assert.deepEqual(errors,[]);
  await ctx.route('**/script.js?*',r=>r.fulfill({contentType:'text/javascript',body:''}));
  const feed=await ctx.newPage();await feed.goto('http://127.0.0.1:4180/index.html');
  await feed.locator('#buscarAlbum').fill('Mi búsqueda sin perder');
  const pages=ctx.pages().length;
  await feed.getByRole('button',{name:'Radio ♫'}).click();
  const panelBefore=await feed.locator('#panelRadio').boundingBox();const heading=await feed.locator('#tituloPanelRadio').boundingBox();const dragX=engine===webkit?0:-65,dragY=engine===webkit?-40:48;await feed.mouse.move(heading.x+heading.width/2,heading.y+heading.height/2);await feed.mouse.down();await feed.mouse.move(heading.x+heading.width/2+dragX,heading.y+heading.height/2+dragY,{steps:4});await feed.mouse.up();const panelAfter=await feed.locator('#panelRadio').boundingBox();assert((engine===webkit?panelAfter.y<=panelBefore.y-25:panelAfter.y>=panelBefore.y+25)&&(engine===webkit||panelAfter.x<=panelBefore.x-40),'the floating radio panel can be dragged by its header: '+JSON.stringify({panelBefore,panelAfter,heading}));
  const room=feed.frameLocator('#panelRadio iframe');
  await room.getByRole('searchbox',{name:'Artista',exact:true}).fill('Mi artista');
  await room.getByRole('button',{name:'Entrar a escuchar'}).click();
  await room.getByRole('button',{name:'Volver a la canción de la sala'}).waitFor();
  await feed.getByRole('button',{name:'Minimizar sin detener la radio'}).click();
  assert.match(await feed.locator('#tituloPanelRadio').innerText(),/La que suena al volver/,'the minimized radio should display the current track');
  assert.equal(await feed.locator('#miniaturaRadioPanel').isVisible(),true,'the minimized radio shows the current YouTube thumbnail');assert.match(await feed.locator('#miniaturaRadioPanel').getAttribute('src'),/i\.ytimg\.com\/vi\/ponmlkjihgf\/mqdefault\.jpg/);
  assert.equal(await feed.locator('#panelRadio').isVisible(),true);
  assert.equal(await feed.locator('#panelRadio').evaluate(e=>e.classList.contains('minimizado')),true);
  assert.equal(await feed.frameLocator('#panelRadio iframe').locator('#radioReproductor').isVisible(),true);
  assert.equal(await room.locator('body').evaluate(()=>window.pauseCalls),0,'minimizing must not pause the YouTube player');
  await feed.getByRole('button',{name:'Expandir radio'}).click();
  assert.equal(await feed.locator('#panelRadio').evaluate(e=>e.classList.contains('minimizado')),false);
  await feed.getByRole('button',{name:'Cerrar la ventana y mantener la radio'}).click();
  assert.equal(await feed.locator('#panelRadio').evaluate(e=>e.classList.contains('minimizado')),true);
  assert.equal(await room.locator('body').evaluate(()=>window.pauseCalls),0,'closing the panel must minimize without pausing');
  await feed.getByRole('button',{name:'Expandir radio'}).click();
  await feed.getByRole('button',{name:'Detener la radio',exact:true}).click();
  assert.equal(await feed.locator('#panelRadio').isVisible(),false);
  await room.locator('body').evaluate(()=>new Promise(resolve=>setTimeout(resolve,0)));
  assert.equal(await room.locator('body').evaluate(()=>window.pauseCalls),1,'the explicit stop control must pause the player');
  await feed.getByRole('button',{name:'Radio ♫'}).click();
  assert.equal(await room.getByRole('searchbox',{name:'Artista',exact:true}).getAttribute('placeholder'),'Nombre del artista');
  assert.equal(await room.getByRole('searchbox',{name:'Artista',exact:true}).evaluate(e=>e.value),'Mi artista');
  assert.equal(await feed.locator('#buscarAlbum').inputValue(),'Mi búsqueda sin perder');
  assert.equal(ctx.pages().length,pages);
  assert.equal(await feed.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  await feed.screenshot({path:'../../outputs/radio-panel-'+engine.name()+'.png',fullPage:false});
  await room.getByRole('searchbox',{name:'Artista',exact:true}).press('Escape');
  await feed.waitForFunction(()=>document.querySelector('#panelRadio').classList.contains('minimizado'));
  assert.equal(await room.locator('body').evaluate(()=>window.pauseCalls),1,'Escape should minimize without pausing');
  await browser.close();console.log('PASS '+engine.name()+': radio flow, floating panel, minimize/restore, explicit stop, Escape, preserved feed, no new tab, mobile');
 }
 server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
